const { hashText } = require("./security");

// 按商品 id 生成详情页图库路径，避免在每个商品里重复手写五张图地址。
function buildGallery(goodsId) {
  return [
    `/images/goods/${goodsId}/1.jpg`,
    `/images/goods/${goodsId}/2.jpg`,
    `/images/goods/${goodsId}/3.jpg`,
    `/images/goods/${goodsId}/4.jpg`,
    `/images/goods/${goodsId}/5.jpg`,
  ];
}

// 生成项目首次启动时写入 MongoDB 的完整演示数据。
// 这些数据既会被后台管理页面使用，也会被旧商城接口直接读取。
function createSeedData() {
  // 商品分类与二级分类。
  const categories = [
    {
      id: "1",
      name: "毛衣",
      image: "/images/category/1.png",
      children: [{ id: "11", name: "羊绒" }],
    },
    {
      id: "2",
      name: "西服",
      image: "/images/category/2.png",
      children: [
        { id: "21", name: "小西服" },
        { id: "22", name: "职业装" },
      ],
    },
    {
      id: "3",
      name: "皮衣",
      image: "/images/category/3.png",
      children: [
        { id: "31", name: "真皮皮衣" },
        { id: "32", name: "仿皮皮衣" },
      ],
    },
    {
      id: "4",
      name: "连衣裙",
      image: "/images/category/4.png",
      children: [
        { id: "41", name: "半身裙" },
        { id: "42", name: "打底裙" },
      ],
    },
    {
      id: "5",
      name: "牛仔裤",
      image: "/images/category/5.png",
      children: [
        { id: "51", name: "阔腿牛仔裤" },
        { id: "52", name: "紧身牛仔裤" },
      ],
    },
    {
      id: "6",
      name: "T恤",
      image: "/images/category/6.png",
      children: [
        { id: "61", name: "印花T恤" },
        { id: "62", name: "字母T恤" },
      ],
    },
    {
      id: "7",
      name: "运动装",
      image: "/images/category/7.png",
      children: [
        { id: "71", name: "春季运动装" },
        { id: "72", name: "秋季运动装" },
      ],
    },
    {
      id: "8",
      name: "短裙",
      image: "/images/category/8.png",
      children: [
        { id: "81", name: "宽松" },
        { id: "82", name: "包臀" },
      ],
    },
    {
      id: "9",
      name: "礼服",
      image: "/images/category/9.png",
      children: [
        { id: "91", name: "晚礼服" },
        { id: "92", name: "婚纱" },
      ],
    },
    {
      id: "10",
      name: "风衣",
      image: "/images/category/10.png",
      children: [
        { id: "101", name: "中长款" },
        { id: "102", name: "长款" },
      ],
    },
  ];

  // 商品主数据。
  const products = [
    {
      id: "001",
      serialNumber: "6901435325888",
      name: "法国代购新款江疏影同款翻领修身中长裙春夏印花连衣裙",
      subtitle: "轻奢印花设计，适合春夏通勤与度假场景",
      categoryId: "4",
      secondCategoryId: "41",
      cover: "/images/goods/001/cover.jpg",
      gallery: buildGallery("001"),
      presentPrice: 98.88,
      oriPrice: 108.88,
      stock: 10000,
      sales: 1280,
      status: "on_sale",
      isHot: true,
      isRecommend: true,
      tags: ["新品", "连衣裙", "春夏"],
      shopId: "SHOP-10001",
      description: "修身版型搭配柔和印花，适合商城首页推荐与活动主推。",
    },
    {
      id: "002",
      serialNumber: "6901435325889",
      name: "柔美而精致圆领金银丝春季毛衣羊毛开衫女短款白外套",
      subtitle: "轻柔羊毛触感，适配高复购女装人群",
      categoryId: "1",
      secondCategoryId: "11",
      cover: "/images/goods/002/cover.jpg",
      gallery: buildGallery("002"),
      presentPrice: 229.9,
      oriPrice: 320.99,
      stock: 8600,
      sales: 932,
      status: "on_sale",
      isHot: true,
      isRecommend: true,
      tags: ["羊绒", "开衫", "高客单"],
      shopId: "SHOP-10001",
      description: "高客单春季毛衣单品，可用于直播间和会员专区活动。",
    },
    {
      id: "003",
      serialNumber: "6901435325890",
      name: "明星同款高端西服春装新款韩版英伦风短款格子小西装女外套",
      subtitle: "职场轻商务爆款，支持通勤与会务穿搭",
      categoryId: "2",
      secondCategoryId: "21",
      cover: "/images/goods/003/cover.jpg",
      gallery: buildGallery("003"),
      presentPrice: 318.88,
      oriPrice: 388.88,
      stock: 7200,
      sales: 655,
      status: "on_sale",
      isHot: true,
      isRecommend: true,
      tags: ["西装", "职场", "英伦"],
      shopId: "SHOP-10001",
      description: "适合作为职业装专区商品，支持首页首屏轮播联动。",
    },
    {
      id: "004",
      serialNumber: "6901435325891",
      name: "复古廓形机车进口绵羊皮衣真皮外套女E142",
      subtitle: "高质感真皮外套，适合做品牌形象商品",
      categoryId: "3",
      secondCategoryId: "31",
      cover: "/images/goods/004/cover.jpg",
      gallery: buildGallery("004"),
      presentPrice: 238.99,
      oriPrice: 248.99,
      stock: 6500,
      sales: 488,
      status: "on_sale",
      isHot: false,
      isRecommend: true,
      tags: ["真皮", "机车风", "品牌款"],
      shopId: "SHOP-10001",
      description: "适合作为精品专场和客单价拉升产品使用。",
    },
    {
      id: "005",
      serialNumber: "6901435325892",
      name: "单排扣高腰牛仔裤女春夏薄款紧身弹力小脚裤显瘦百搭网红浅色长裤",
      subtitle: "高销量基础款，适合搭配活动凑单",
      categoryId: "5",
      secondCategoryId: "52",
      cover: "/images/goods/005/cover.jpg",
      gallery: buildGallery("005"),
      presentPrice: 588.99,
      oriPrice: 888.88,
      stock: 4200,
      sales: 390,
      status: "on_sale",
      isHot: false,
      isRecommend: true,
      tags: ["牛仔裤", "显瘦", "搭配款"],
      shopId: "SHOP-10001",
      description: "搭配销售型商品，适合与上衣组合成套餐营销。",
    },
    {
      id: "006",
      serialNumber: "6901435325893",
      name: "MIUCO女装夏季重工星星烫钻圆领短袖宽松显瘦百搭T恤上衣",
      subtitle: "高毛利T恤品类，适合做爆品与清仓活动",
      categoryId: "6",
      secondCategoryId: "61",
      cover: "/images/goods/006/cover.jpg",
      gallery: buildGallery("006"),
      presentPrice: 1028.88,
      oriPrice: 1888.88,
      stock: 2300,
      sales: 216,
      status: "on_sale",
      isHot: false,
      isRecommend: false,
      tags: ["T恤", "夏装", "烫钻"],
      shopId: "SHOP-10001",
      description: "适合活动专区、秒杀专区和高毛利推荐位。",
    },
    {
      id: "007",
      serialNumber: "6901435325894",
      name: "春夏一步裙包臀裙开叉弹力修身显瘦短裙黑色高腰职业半身裙",
      subtitle: "职业半身裙品类，适合职场女装专题运营",
      categoryId: "8",
      secondCategoryId: "82",
      cover: "/images/goods/007/cover.jpg",
      gallery: buildGallery("007"),
      presentPrice: 2388.66,
      oriPrice: 2888.88,
      stock: 1800,
      sales: 125,
      status: "on_sale",
      isHot: false,
      isRecommend: false,
      tags: ["短裙", "职业装", "高腰"],
      shopId: "SHOP-10001",
      description: "适合会员专享区和高端客群的精品陈列。",
    },
    {
      id: "008",
      serialNumber: "6901435325895",
      name: "夏季新款短袖圆领紧身小黑超短裙开叉包臀性感连衣裙夜店女装",
      subtitle: "视觉冲击强，适合活动主题和首页引流位",
      categoryId: "4",
      secondCategoryId: "42",
      cover: "/images/goods/008/cover.jpg",
      gallery: buildGallery("008"),
      presentPrice: 666.88,
      oriPrice: 888.88,
      stock: 3500,
      sales: 298,
      status: "draft",
      isHot: false,
      isRecommend: false,
      tags: ["夜店风", "短裙", "引流款"],
      shopId: "SHOP-10001",
      description: "更适合专题活动而非默认陈列，初始设为草稿商品。",
    },
  ];

  return {
    // 系统级配置。
    settings: {
      shopName: "Girl Shop 商业演示后台",
      currency: "CNY",
      supportEmail: "ops@girlshop.local",
      version: "2.0.0",
      sessionHours: 12,
    },
    // 默认后台管理员账号。
    adminUsers: [
      {
        id: "ADMIN-001",
        username: "admin",
        passwordHash: hashText("Admin@123456"),
        name: "超级管理员",
        role: "super_admin",
        status: "enabled",
        lastLoginAt: "",
      },
    ],
    categories,
    products,
    // 首页频道 Tab 配置。
    homeTabs: [
      {
        id: "001",
        name: "推荐",
        normalImage: "/images/homecategory/normal001_1.png",
        selectedImage: "/images/homecategory/selected001_1.png",
      },
      {
        id: "002",
        name: "彩票",
        normalImage: "/images/homecategory/normal001_2.png",
        selectedImage: "/images/homecategory/selected001_2.png",
      },
      {
        id: "003",
        name: "棋牌",
        normalImage: "/images/homecategory/normal001_3.png",
        selectedImage: "/images/homecategory/selected001_3.png",
      },
      {
        id: "004",
        name: "电竞",
        normalImage: "/images/homecategory/normal001_4.png",
        selectedImage: "/images/homecategory/selected001_4.png",
      },
      {
        id: "005",
        name: "体育",
        normalImage: "/images/homecategory/normal001_5.png",
        selectedImage: "/images/homecategory/selected001_5.png",
      },
    ],
    // 首页不同频道下的内容块。
    homeSections: {
      "001": [
        { goodsId: "1001", image: "/images/homedetail/001_1.png", goodsName: "推荐位商品" },
        { goodsId: "1002", image: "/images/homedetail/001_2.png", goodsName: "推荐位商品" },
      ],
      "002": [
        { goodsId: "2001", image: "/images/homedetail/002_1.png", goodsName: "彩票位商品" },
        { goodsId: "2002", image: "/images/homedetail/002_2.png", goodsName: "彩票位商品" },
        { goodsId: "2003", image: "/images/homedetail/002_1.png", goodsName: "彩票位商品" },
        { goodsId: "2004", image: "/images/homedetail/002_2.png", goodsName: "彩票位商品" },
      ],
      "003": [
        { goodsId: "3001", image: "/images/homedetail/003_1.png", goodsName: "棋牌位商品" },
        { goodsId: "3002", image: "/images/homedetail/003_1.png", goodsName: "棋牌位商品" },
        { goodsId: "3003", image: "/images/homedetail/003_1.png", goodsName: "棋牌位商品" },
      ],
      "004": [
        { goodsId: "4001", image: "/images/homedetail/004_1.png", goodsName: "电竞位商品" },
        { goodsId: "4002", image: "/images/homedetail/004_1.png", goodsName: "电竞位商品" },
        { goodsId: "4003", image: "/images/homedetail/004_1.png", goodsName: "电竞位商品" },
      ],
      "005": [
        { goodsId: "5001", image: "/images/homedetail/005_1.png", goodsName: "体育位商品" },
        { goodsId: "5002", image: "/images/homedetail/005_1.png", goodsName: "体育位商品" },
        { goodsId: "5003", image: "/images/homedetail/005_1.png", goodsName: "体育位商品" },
      ],
    },
    // 首页轮播图。
    banners: [
      { id: "BANNER-001", image: "/images/banner/1.jpeg", goodsId: "001", title: "首页主视觉 1", sort: 1, status: "published" },
      { id: "BANNER-002", image: "/images/banner/2.jpeg", goodsId: "002", title: "首页主视觉 2", sort: 2, status: "published" },
      { id: "BANNER-003", image: "/images/banner/3.jpeg", goodsId: "003", title: "首页主视觉 3", sort: 3, status: "published" },
      { id: "BANNER-004", image: "/images/banner/4.jpeg", goodsId: "004", title: "首页主视觉 4", sort: 4, status: "published" },
    ],
    // 首页楼层广告与楼层商品。
    floorSections: [
      {
        id: "floor1",
        bannerImage: "/images/advert/ad02.png",
        bannerToPlace: "4",
        items: [
          { image: "/images/floor/1.png", goodsId: "001" },
          { image: "/images/floor/2.png", goodsId: "002" },
          { image: "/images/floor/3.png", goodsId: "003" },
          { image: "/images/floor/4.png", goodsId: "004" },
          { image: "/images/floor/5.png", goodsId: "005" },
        ],
      },
    ],
    // 会员用户演示数据。
    users: [
      {
        id: "U1001",
        nickname: "林小夏",
        phone: "13800000001",
        email: "linxiaoxia@example.com",
        level: "VIP1",
        status: "enabled",
        city: "上海",
        totalSpent: 1888.66,
        orderCount: 5,
        registeredAt: "2026-01-03 10:00:00",
        lastLoginAt: "2026-04-08 09:20:00",
      },
      {
        id: "U1002",
        nickname: "周可可",
        phone: "13800000002",
        email: "zhoukeke@example.com",
        level: "VIP2",
        status: "enabled",
        city: "杭州",
        totalSpent: 4288.18,
        orderCount: 9,
        registeredAt: "2025-11-18 14:35:00",
        lastLoginAt: "2026-04-07 20:10:00",
      },
      {
        id: "U1003",
        nickname: "苏安安",
        phone: "13800000003",
        email: "suanan@example.com",
        level: "普通会员",
        status: "disabled",
        city: "北京",
        totalSpent: 688.88,
        orderCount: 1,
        registeredAt: "2026-02-11 08:22:00",
        lastLoginAt: "2026-03-26 17:02:00",
      },
      {
        id: "U1004",
        nickname: "许晨曦",
        phone: "13800000004",
        email: "xuchenxi@example.com",
        level: "VIP1",
        status: "enabled",
        city: "深圳",
        totalSpent: 2680.5,
        orderCount: 4,
        registeredAt: "2025-12-20 12:12:00",
        lastLoginAt: "2026-04-08 08:48:00",
      },
    ],
    // 订单演示数据。
    orders: [
      {
        id: "O202604080001",
        userId: "U1001",
        userName: "林小夏",
        status: "paid",
        totalAmount: 98.88,
        createdAt: "2026-04-08 09:15:00",
        payAt: "2026-04-08 09:17:00",
        address: "上海市浦东新区世纪大道 100 号",
        items: [{ productId: "001", productName: "法国代购新款江疏影同款翻领修身中长裙春夏印花连衣裙", quantity: 1, price: 98.88 }],
      },
      {
        id: "O202604070021",
        userId: "U1002",
        userName: "周可可",
        status: "shipped",
        totalAmount: 548.78,
        createdAt: "2026-04-07 19:20:00",
        payAt: "2026-04-07 19:26:00",
        address: "杭州市西湖区文三路 88 号",
        items: [
          { productId: "002", productName: "柔美而精致圆领金银丝春季毛衣羊毛开衫女短款白外套", quantity: 1, price: 229.9 },
          { productId: "004", productName: "复古廓形机车进口绵羊皮衣真皮外套女E142", quantity: 1, price: 318.88 },
        ],
      },
      {
        id: "O202604050113",
        userId: "U1004",
        userName: "许晨曦",
        status: "completed",
        totalAmount: 907.87,
        createdAt: "2026-04-05 12:03:00",
        payAt: "2026-04-05 12:08:00",
        address: "深圳市南山区科技园南区 12 栋",
        items: [
          { productId: "003", productName: "明星同款高端西服春装新款韩版英伦风短款格子小西装女外套", quantity: 1, price: 318.88 },
          { productId: "005", productName: "单排扣高腰牛仔裤女春夏薄款紧身弹力小脚裤显瘦百搭网红浅色长裤", quantity: 1, price: 588.99 },
        ],
      },
      {
        id: "O202604010007",
        userId: "U1003",
        userName: "苏安安",
        status: "cancelled",
        totalAmount: 666.88,
        createdAt: "2026-04-01 17:30:00",
        payAt: "",
        address: "北京市朝阳区望京 SOHO",
        items: [{ productId: "008", productName: "夏季新款短袖圆领紧身小黑超短裙开叉包臀性感连衣裙夜店女装", quantity: 1, price: 666.88 }],
      },
    ],
  };
}

module.exports = createSeedData;
